### ISSUE TITLE
[Bug] Can't right click on scenes anymore

### ISSUE THREAD

**Issue by Xqua** [DM-miX/scene-transitions#15]
After installing Scene Transition, I get this bug when I right-click on a scene.
```
Uncaught TypeError: Cannot read property 'getFlag' of undefined
[Detected 1 package: scene-transitions]
    at Object.condition (scene-transitions.js:77)
    at ContextMenu.render (foundry.js:43494)
    at HTMLLIElement.<anonymous> (foundry.js:43437)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.v.handle (jquery.min.js:2)
```

**Comment by coffiarts** [comment]
Same for me. Seems to be an incompatibility with foundry vtt v9.

**Comment by DM-miX** [comment]
Ah sorry - my game has been on hiatus for a few months so haven’t been keeping up to date. 
Will take a look when I’m back in front a laptop

**Comment by Melephisance** [comment]
Same here - v 9.241. Right click on any scene within the scene directory no longer works for me. Let me know if I can be of any assistance :)

**Comment by RavenknightDM** [comment]
The one module that keeps me from upgrading to v9. :D

**Comment by DM-miX** [comment]
On it - have been away on holiday
