### ISSUE TITLE
Feature Request: Option to only fade canvas, not UI

### ISSUE THREAD

**Issue by LebombJames** [DM-miX/scene-transitions#7]
Currently, the module fades the entire Foundry window, UI and all. It would be great if there was an option to only fade the canvas, so a user wouldn't be interrupted while using their character sheet or something. Would also be good for GMs as they don't have to wait for the animation to finish, they can continue getting things ready as appropriate.

**Comment by DM-miX** [comment]
Yeah there's some intersting things with the UI since 0.8.
In reality it fades in, as opposed to faading everytihng else out so it's just a matter of setting it in the right place :)
I'll look at adding an option to fade all, or just the canvas.

**Comment by DM-miX** [comment]
Available in 0.2.1. New option Show User Interface (macro: showUI)
