### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'audioFadeTimer' before initialization

### ISSUE THREAD

**Issue by coffiarts** [DM-miX/scene-transitions#8]
I consistently get the exception...

scene-transitions.js:323 Uncaught ReferenceError: Cannot access 'audioFadeTimer' before initialization
    at fade (scene-transitions.js:323)
    at Transition.fadeAudio (scene-transitions.js:326)
    at Transition.destroy (scene-transitions.js:274)
    at Transition.<anonymous> (scene-transitions.js:263)

... whenever I run a Transition with the following code:

> Transition.macro(
	{
		sceneID: <mySceneID>,
		content:"",
		fontColor:'#ffffff',
		fontSize:'28px',
		bgImg:'', // pass any relative or absolute image url here.
		bgPos:'center center',
		bgSize:'cover',
		bgColor:'#000000',
		bgOpacity:0.7,
		fadeIn: 1000, //how long to fade in
		delay:2000, //how long for transition to stay up
		fadeOut: 1000, //how long to fade out
		audio: "modules/tabletop-rpg-music/music/DreamsofElysium.mp3",
			volume:.3,
		skippable:true, //Allows players to skip transition with a click before delay runs out.
		gmHide: true, // hide the transistion on other windows logged in as a GM
		gmEndAll: true, // whwn the fm clicks to end the transition - end for everyone
	}, true
);

The error can be bypassed by changing fadeOut to 0 (which disables the fading and thus isn't an option).

As an experiment, I could get rid of the error by "hacking in" a try / catch surrounding the clearInterval(...) line in scene-transitions.js:323 (which may give a hint to possible solutions?):

> let fade = function() {
                volume -= speed;
                audio.gain.value = volume.toFixed(6);
                if(volume.toFixed(6) <= targetVolume){
                    audio.stop();
                    try { 
						clearInterval(audioFadeTimer);
					} catch(e) {}
                };
            }

**Comment by DM-miX** [comment]
Interesting... what version of Foundry are you running?

**Comment by coffiarts** [comment]
> Interesting... what version of Foundry are you running?
Thx for your reply on this, I appreciate your help! I am on 0.8.9. Still using my "hack" shown above.

**Comment by DM-miX** [comment]
ah yeah, it says 0.8.6, but it works fine with 0.8.9.
I'm not seeing the error here. BUT - just under that I switched the 2 lines so audioFadeTimer is declared before the first fade. Hopefully that fixes it.
Will post an update later today
