### ISSUE TITLE
Feature Request: Mantain Transition until GM ends it

### ISSUE THREAD

**Issue by turboraton** [DM-miX/scene-transitions#9]
Hey there friend. MANY thanks for you awesome module, I'd love to request a simple feature, the ability to mantain the scene transition until I, as a GM end it. I use the transition as a canvas to roleplay and when it calls for action or exploration, I start the map. (actually, would it be possible to add more than one image to the transitions?)

**Comment by DM-miX** [comment]
Hi Turbo - I think I was working on just that a while ago for the same reason! but had problems where even the GM couldn't end the transition, now that someone else wants it I'll have another go

**Comment by DM-miX** [comment]
Hi Turbo - just checked, you can already do this!

Set skippable to false
Set delay to a big number ie. 100000000 seconds
Check the box GM ends for all (gmEndAll in macro).
